package com.vibelock.app.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.vibelock.app.ai.GeminiEngine
import com.vibelock.app.ai.WeeklyData
import com.vibelock.app.ui.components.AuraGlassCard
import com.vibelock.app.ui.components.NeonText
import com.vibelock.app.ui.theme.AuraColors
import kotlinx.coroutines.launch
import androidx.compose.ui.draw.clip
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack

@Composable
fun AIInsightsScreen(
    geminiEngine: GeminiEngine,
    weeklyData: WeeklyData,
    onBack: () -> Unit
) {
    var reportText by remember { mutableStateOf("Generating your Aura Archetype...") }
    var isLoading by remember { mutableStateOf(true) }
    val coroutineScope = rememberCoroutineScope()

    LaunchedEffect(Unit) {
        reportText = geminiEngine.generateWeeklyVibeReport(weeklyData)
        isLoading = false
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFF050505))
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        // Top Bar
        Row(
            modifier = Modifier.fillMaxWidth().padding(bottom = 16.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(
                onClick = onBack,
                modifier = Modifier
                    .clip(androidx.compose.foundation.shape.CircleShape)
                    .background(Color(0xFF1E1E1E))
            ) {
                Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = Color.White)
            }
            Spacer(modifier = Modifier.weight(1f))
        }

        NeonText(
            text = "AURA INTELLIGENCE",
            style = androidx.compose.ui.text.TextStyle(
                fontSize = 24.sp,
                fontWeight = FontWeight.Black,
                letterSpacing = 2.sp
            )
        )
        Text(
            text = "Powered by Gemini AI ✨",
            color = Color.Gray,
            fontSize = 14.sp,
            modifier = Modifier.padding(top = 4.dp, bottom = 32.dp)
        )

        // SECTION 1: Weekly Vibe Report Card
        AuraGlassCard(
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(modifier = Modifier.padding(20.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = "THIS WEEK'S REPORT",
                        color = Color(0xFF8B5CF6),
                        fontSize = 12.sp,
                        fontWeight = FontWeight.Bold
                    )
                    if (isLoading) {
                        CircularProgressIndicator(
                            modifier = Modifier.size(16.dp),
                            color = Color(0xFF8B5CF6),
                            strokeWidth = 2.dp
                        )
                    } else {
                        TextButton(
                            onClick = {
                                isLoading = true
                                reportText = "Re-analyzing your vibes..."
                                coroutineScope.launch {
                                    reportText = geminiEngine.generateWeeklyVibeReport(weeklyData)
                                    isLoading = false
                                }
                            },
                            contentPadding = PaddingValues(0.dp),
                            modifier = Modifier.height(24.dp)
                        ) {
                            Text("Refresh", color = Color.Gray, fontSize = 12.sp)
                        }
                    }
                }
                Spacer(modifier = Modifier.height(16.dp))
                
                Text(
                    text = reportText,
                    color = Color.White,
                    fontSize = 16.sp,
                    lineHeight = 24.sp
                )

                Spacer(modifier = Modifier.height(16.dp))
                Text(
                    text = "Generated by Gemini AI",
                    color = Color.DarkGray,
                    fontSize = 10.sp,
                    modifier = Modifier.align(Alignment.End)
                )
            }
        }

        Spacer(modifier = Modifier.height(32.dp))

        // SECTION 2: Pattern Analysis
        Text(
            text = "YOUR AURA PATTERNS",
            color = Color.White,
            fontWeight = FontWeight.Bold,
            fontSize = 16.sp,
            modifier = Modifier
                .align(Alignment.Start)
                .padding(bottom = 16.dp)
        )

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            PatternCard(
                emoji = "🕐",
                title = "Peak Hours",
                desc = "You vibe best at 11 PM — Night Owl confirmed.",
                modifier = Modifier.weight(1f)
            )
            PatternCard(
                emoji = "🎯",
                title = "Dominant Vibe",
                desc = "${weeklyData.dominantVibe} is 42% of your check-ins.",
                modifier = Modifier.weight(1f)
            )
        }

        Spacer(modifier = Modifier.height(16.dp))

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            PatternCard(
                emoji = "🔥",
                title = "Streak Analysis",
                desc = "Your avg streak is 8 days. You always break on Thursdays \uD83D\uDE2C",
                modifier = Modifier.weight(1f)
            )
            PatternCard(
                emoji = "📈",
                title = "Growth Rate",
                desc = "XP/week up 34% from last month. You're ascending.",
                modifier = Modifier.weight(1f)
            )
        }

        Spacer(modifier = Modifier.height(32.dp))

        // SECTION 3: Interesting Facts
        Text(
            text = "DAILY PSYCHOLOGY INSIGHT",
            color = Color.White,
            fontWeight = FontWeight.Bold,
            fontSize = 16.sp,
            modifier = Modifier
                .align(Alignment.Start)
                .padding(bottom = 16.dp)
        )

        AuraGlassCard(modifier = Modifier.fillMaxWidth()) {
            val dailyFact = remember {
                listOf(
                    "Did you know? Building a 21-day streak physically rewires your brain's dopamine pathways.",
                    "Gen-Z focuses 40% more on 'vibes' than the previous generation. Your aura actually matters.",
                    "People with a 'Grind' dominant vibe are 70% more likely to reach their goals within a year.",
                    "Checking in at the exact same time every day builds a 'habit loop' faster than anything else."
                ).random()
            }
            Column(modifier = Modifier.padding(16.dp)) {
                Text(text = "🧠 Did you know?", color = AuraColors.NeonCyan, fontWeight = FontWeight.Bold, fontSize = 14.sp)
                Spacer(modifier = Modifier.height(8.dp))
                Text(text = dailyFact, color = Color.LightGray, fontSize = 14.sp, lineHeight = 20.sp)
            }
        }
        
        Spacer(modifier = Modifier.height(32.dp))
    }
}

@Composable
fun PatternCard(emoji: String, title: String, desc: String, modifier: Modifier = Modifier) {
    AuraGlassCard(modifier = modifier.height(140.dp)) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(text = emoji, fontSize = 20.sp)
                Spacer(modifier = Modifier.width(8.dp))
                Text(text = title, color = Color.White, fontWeight = FontWeight.Bold, fontSize = 14.sp)
            }
            Spacer(modifier = Modifier.height(12.dp))
            Text(text = desc, color = Color.LightGray, fontSize = 12.sp, lineHeight = 16.sp)
        }
    }
}
